config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :treatments

  authenticated :user do
    root "treatments#index", as: "authenticated_root"
  end

  devise_scope :user do
    root to: "devise/sessions#new"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :user

  has_attached_file :file1
  has_attached_file :file2
  has_attached_file :result
  validates :file1, :file2, attachment_presence: true
  do_not_validate_attachment_file_type :file1, :file2

  after_commit :generate_result


  def generate_result
    input1 = {}
    File.open(self.file1.path).each_line do |line|
      input1[line] = ""
    end

    open('public/' + self.id.to_s, 'w') do |f|
      File.open(self.file2.path).each_line do |line|
        if input1.key?(line)
          f << line
        end
      end
    end

  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :treatments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]

  # GET /treatments
  # GET /treatments.json
  def index
    @treatments = Treatment.where(user_id: current_user)
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show
  end

  # GET /treatments/new
  def new
    @treatment = current_user.treatments.build
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = current_user.treatments.build(treatment_params)
    respond_to do |format|
      if @treatment.save
        #q1(@treatment.file1.url(:original, false), @treatment.file2.url(:original, false))
        format.html { redirect_to @treatment, notice: 'Treatment was successfully created.' }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1
  # PATCH/PUT /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to @treatment, notice: 'Treatment was successfully updated.' }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment.destroy
    respond_to do |format|
      format.html { redirect_to treatments_url, notice: 'Treatment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treatment_params
      params.require(:treatment).permit(:file1, :file2, :result)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Filetreatment</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/treatments/_form.html.erb
<%= form_with(model: treatment, local: true) do |form| %>
  <% if treatment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
      <% treatment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :file1 %>
    <%= form.file_field :file1, id: :treatment_file1 %>
  </div>

  <div class="field">
    <%= form.label :file2 %>
    <%= form.file_field :file2, id: :treatment_file2 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/treatments/edit.html.erb
<h1>Editing Treatment</h1>

<%= render 'form', treatment: @treatment %>

<%= link_to 'Show', @treatment %> |
<%= link_to 'Back', treatments_path %>

app/views/treatments/index.html.erb
<div class="row" style="margin-top: 50px;">
  <div class="col-sm-8 offset-sm-2">
    <div class="card card-primary">
      <h4 class="card-header">List of Treatments created by <%= current_user.email %></h4>
      <div class="card-body">
        <p id="notice"><%= notice %></p>
        <table class="table">
          <thead>
            <tr>
              <th>File1</th>
              <th>File2</th>
              <th>Result</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @treatments.each do |treatment| %>
              <tr>
                <td><%= link_to "Download", treatment.file1.url(:original, false), { target: '_blank' } %></td>
                <td><%= link_to "Download", treatment.file2.url(:original, false), { target: '_blank' } %></td>
                <td><%= link_to "Download", '/' + treatment.id.to_s, { target: '_blank' } %></td>
                <td><%= link_to 'Show', treatment %></td>
                <td><%= link_to 'Edit', edit_treatment_path(treatment) %></td>
                <td><%= link_to 'Destroy', treatment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%= link_to 'New Treatment', new_treatment_path %>
        <br><br>
        <%= link_to 'Sign Out', root_path + "users/sign_out" %>
      </div>
    </div>
  </div>
</div>

app/views/treatments/new.html.erb
<h1>New Treatment</h1>

<%= render 'form', treatment: @treatment %>

<%= link_to 'Back', treatments_path %>

app/views/treatments/show.html.erb
<div class="row" style="margin-top: 50px;">
  <div class="col-sm-8 offset-sm-2">
    <div class="card card-primary">
      <div class="card-body">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>File1:</strong>
          <%= link_to "Download", @treatment.file1.url(:original, false), { target: '_blank' } %>
        </p>

        <p>
          <strong>File2:</strong>
          <%= link_to "Download", @treatment.file2.url(:original, false), { target: '_blank' } %>
        </p>

        <p>
          <strong>Result:</strong>
          <%= link_to "Download", '/' + @treatment.id.to_s, { target: '_blank' } %>
        </p>

        <p>
          <strong>Created by:</strong>
          <%= current_user.email %>
        </p>

        <p>
          <strong><%= time_ago_in_words(@treatment.created_at) %></strong> ago created!
        </p>

        <%= link_to 'Edit', edit_treatment_path(@treatment) %> |
        <%= link_to 'Back', treatments_path %>
        <br><br>
        <%= link_to 'Sign Out', root_path + "users/sign_out" %>
      </div>
    </div>
  </div>
</div>